overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel-odsw.yml
targets:
  - README.rst: odsw-README.rst.jj2
  - setup.py: custom-setup.py.jj2
  - requirements.txt: custom-requirements.txt.jj2
  - "tests/requirements.txt": "tests/custom-requirements.txt.jj2"
  - .travis.yml: custom_travis.yml.jj2
  - "pyexcel_odsw/_version.py": version.py.jj2

